server:
  port: 80

spring:
  application:
    name: order-hystrix-80

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7000.com:7000/eureka/
      defaultZone: http://eureka7000.com:7000/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true