server:
  port: 3344

spring:
  application:
    name: cloud-config-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UserManZhou/springcloud-springconfig.git
          search-paths:
            - springcloud-springconfig
        label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  instance:
    # 设置当前实例别名
    instance-id: "config-3344"
    # 开启IP连接
    prefer-ip-address: true
    # 表示eureka服务器从收到消息后等待的时间(单位为秒)
    lease-expiration-duration-in-seconds: 2
    # 表示eureka客户端需要发送心跳的频率(以秒为单位)
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      #      集群模式
      #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7000.com:7000/eureka/
      #   单机模式
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
