server:
  port: 8083

spring:
  application:
    name: pay-hystrix-8083

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7000.com:7000/eureka/

