
server:
  port: 8083
spring:
  application:
    name: pay-consul-Mircservice
  #consul 信息配置
  cloud:
    consul:
      host: localhost #consul注册中心的ip地址
      port: 8500 #consul注册中心端口
      discovery:
        service-name: ${spring.application.name} #服务的名称
        instance-id: ${spring.application.name}-${server.port}
        hostname: 127.0.0.1
#        register: true #是否需要注册
#        prefer-ip-address: true #开启ip地址注册
#        ip-address: ${spring.cloud.client.ip-ad
#logging:
#  file:
#    name: F:\\JavaCode\\SpringCloud\\springcloud-payMircservice-consul-8083\\log\\consul.log
#  pattern:
#    console: %d{yyyy-MM-dd} [%thread] [%-5level] %logger{50}
#    level:
#      org.springframework: INFO

