server:
  port: 90

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.234.136:1111
#        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"